### ISSUE TITLE
Missing requirements.txt file

### ISSUE THREAD

**Issue by PeterBartram** [Shrimat/lumi_pachack#2]
Hi there, was looking to download and run this source code but the requirements.txt file is missing - do you think you could upload it to save me manually installing dependencies? Thanks!

**Comment by Shrimat** [comment]
Hi Pete,

Sorry about that, I think we forgot to actually upload the file.

I have just pushed the requirements.txt file to the repository, hopefully,
the dependencies should be installed now.

Kind regards,

Shrimat Kapoor

**Comment by PeterBartram** [comment]
Amazing, thanks for uploading. Everything is running on this end now, thanks! Pete
